import React, { useEffect, useRef, useMemo } from 'react';
import {
  View,
  Text,
  StyleSheet,
  TouchableOpacity,
  SafeAreaView,
  Animated,
} from 'react-native';
import Icon from 'react-native-vector-icons/Ionicons';

/* ---------------- AI RISK GENERATOR ---------------- */

function generateRisk(severity) {
  if (severity === 'High') {
    const value = Math.floor(75 + Math.random() * 20); // 75–95
    return { label: 'High Risk Scam', value, color: '#DC2626' };
  }

  if (severity === 'Medium') {
    const value = Math.floor(40 + Math.random() * 35); // 40–74
    return { label: 'Medium Risk Scam', value, color: '#F59E0B' };
  }

  const value = Math.floor(5 + Math.random() * 35); // 5–39
  return { label: 'Low Risk Scam', value, color: '#10B981' };
}

export default function ReportSuccessScreen({ route, navigation }) {
  const {
    source = 'Unknown',
    category = 'Scam',
    severity = 'Medium',
  } = route?.params || {};

  const scaleAnim = useRef(new Animated.Value(0.85)).current;
  const fadeAnim = useRef(new Animated.Value(0)).current;

  /* ---------------- AI RESULT ---------------- */

  const risk = useMemo(() => generateRisk(severity), [severity]);

  useEffect(() => {
    Animated.parallel([
      Animated.spring(scaleAnim, {
        toValue: 1,
        friction: 5,
        useNativeDriver: true,
      }),
      Animated.timing(fadeAnim, {
        toValue: 1,
        duration: 600,
        useNativeDriver: true,
      }),
    ]).start();
  }, []);

  return (
    <SafeAreaView style={styles.container}>
      {/* SUCCESS ICON */}
      <Animated.View
        style={[
          styles.iconWrap,
          { transform: [{ scale: scaleAnim }], opacity: fadeAnim },
        ]}
      >
        <Icon name="checkmark-circle" size={78} color="#2563EB" />
      </Animated.View>

      {/* TITLE */}
      <Animated.View style={{ opacity: fadeAnim }}>
        <Text style={styles.title}>Report Submitted</Text>
        <Text style={styles.subtitle}>
          Thanks for helping protect the Insightify community
        </Text>
      </Animated.View>

      {/* RESULT CARD */}
      <Animated.View
        style={[
          styles.resultCard,
          { opacity: fadeAnim, transform: [{ scale: scaleAnim }] },
        ]}
      >
        <Text style={styles.resultLabel}>AI Scam Assessment</Text>

        <View style={styles.percentRow}>
          <Text style={styles.percent}>{risk.value}%</Text>
          <Text style={[styles.risk, { color: risk.color }]}>
            {risk.label}
          </Text>
        </View>

        <View style={styles.progressTrack}>
          <View
            style={[
              styles.progressFill,
              {
                width: `${risk.value}%`,
                backgroundColor: risk.color,
              },
            ]}
          />
        </View>

        <Text style={styles.explain}>
          This result is generated by AI using scam patterns, behavior analysis,
          and community reports.
        </Text>

        {/* META INFO */}
        <View style={styles.metaRow}>
          <MetaItem icon="alert-circle-outline" label={category} />
          <MetaItem icon="call-outline" label={source} />
          <MetaItem icon="speedometer-outline" label={severity} />
        </View>
      </Animated.View>

      {/* COMMUNITY IMPACT */}
      <View style={styles.impactCard}>
        <Icon name="people-outline" size={20} color="#2563EB" />
        <Text style={styles.impactText}>
          Your report may appear in the community feed to warn other users and
          improve scam detection accuracy.
        </Text>
      </View>

      {/* ACTIONS */}
      <View style={styles.footerActions}>
        <TouchableOpacity
          style={styles.primaryBtn}
          onPress={() => navigation.replace('ReportHome')}
        >
          <Text style={styles.primaryText}>Report Another Scam</Text>
        </TouchableOpacity>

        <TouchableOpacity
          style={styles.secondaryBtn}
          onPress={() => navigation.navigate('Feed')}
        >
          <Text style={styles.secondaryText}>View Community Feed</Text>
        </TouchableOpacity>
      </View>
    </SafeAreaView>
  );
}

/* ---------------- SMALL COMPONENT ---------------- */

function MetaItem({ icon, label }) {
  return (
    <View style={styles.metaItem}>
      <Icon name={icon} size={16} color="#2563EB" />
      <Text style={styles.metaText}>{label}</Text>
    </View>
  );
}

/* ---------------- STYLES ---------------- */

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F7FAFF',
    alignItems: 'center',
    padding: 20,
    paddingBottom: 36,
  },

  iconWrap: {
    marginTop: 28,
  },

  title: {
    fontSize: 22,
    fontWeight: '900',
    color: '#0F172A',
    marginTop: 14,
  },

  subtitle: {
    textAlign: 'center',
    color: '#64748B',
    marginTop: 6,
    marginBottom: 24,
    fontSize: 13,
  },

  resultCard: {
    width: '100%',
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 20,
    elevation: 5,
  },

  resultLabel: {
    fontSize: 13,
    fontWeight: '800',
    color: '#64748B',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },

  percentRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    marginTop: 10,
  },

  percent: {
    fontSize: 38,
    fontWeight: '900',
    color: '#2563EB',
  },

  risk: {
    marginLeft: 10,
    fontWeight: '900',
    fontSize: 14,
  },

  progressTrack: {
    height: 10,
    backgroundColor: '#E5E7EB',
    borderRadius: 10,
    marginTop: 12,
    overflow: 'hidden',
  },

  progressFill: {
    height: '100%',
    borderRadius: 10,
  },

  explain: {
    marginTop: 12,
    fontSize: 12,
    color: '#64748B',
    lineHeight: 18,
  },

  metaRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 16,
  },

  metaItem: {
    flexDirection: 'row',
    alignItems: 'center',
  },

  metaText: {
    marginLeft: 6,
    fontSize: 12,
    fontWeight: '700',
    color: '#0F172A',
  },

  impactCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#E8F1FF',
    padding: 14,
    borderRadius: 16,
    marginTop: 20,
  },

  impactText: {
    marginLeft: 10,
    fontSize: 13,
    fontWeight: '600',
    color: '#1E3A8A',
    flex: 1,
  },

  footerActions: {
    width: '100%',
    marginTop: 28,
    alignItems: 'center',
  },

  primaryBtn: {
    backgroundColor: '#2563EB',
    paddingVertical: 16,
    width: '100%',
    borderRadius: 18,
    alignItems: 'center',
    elevation: 4,
  },

  primaryText: {
    color: '#FFFFFF',
    fontWeight: '900',
    fontSize: 16,
  },

  secondaryBtn: {
    marginTop: 14,
    paddingVertical: 14,
  },

  secondaryText: {
    color: '#2563EB',
    fontWeight: '800',
    fontSize: 15,
  },
});